### ISSUE TITLE
Getting Started points to invalid files

### ISSUE THREAD

**Issue by XaaK-zz** [Microsoft/Product-flavor-dimension-sample-app#1]
Several issues with the getting started guide:

- The getting started guide assumes a RainMain folder which does not exist on public 7.3 dev machines.   
- The "\AxPackage\ChocolateyPackages\dirs" file does not exist in this repo.
- The "\AxPackage\ChocolateyPackages\MetaPackagesApplication\PackageTable.csv" file does not exist in this repo.

**Comment by andreygarmash** [comment]
Hi @XaaK, thanks for reporting the issue, few questions/comments:
- Do you mean user has to enlist the repo first before he can get RainMain folder or partners have completely different process?
- I did not include dirs and PackageTable.csv files as these files would become outdated in this repo  while user could mistakenly overwrite those from a more recent build, therefore I'd prefer them edit their files instead (maybe the guide is not clear enough to highlight that files has to edited on a user's environment?).  We could of course script it to make process easier...

**Comment by ReneDunweber** [comment]
Hi @XaaK,

Please take a look at the way it has been structured now.
And also test the PS script that can be used to install models on the VM. 

Also note, that there are a prerequisite section now.
So make sure that the VM is on the right PU and application.

If you have any issues or suggestions for improvements, please let us know .
