### ISSUE TITLE
Models are saved with SYS layer

### ISSUE THREAD

**Issue by XaaK-zz** [Microsoft/Product-flavor-dimension-sample-app#2]
The two models are saved with the layer = 0 (i.e. SYS), which means it is impossible for non-Microsoft developers to modify any elements.  I believe the intent was to provide these as an example to work through - so perhaps this should be set to the ISV layer (8) - much like the Fleet Management sample?

**Comment by ReneDunweber** [comment]
The layer for the ProductFlavor model is now changed to ISV (like the Fleet management) and for the ProductFlavorIntegration model to be the VAR layer. This was the intention to be the layers, when implementing the new abstract, not yet bound to the framework, custom inventory dimension and the layer for the actual integration/binding to the framework and dimension 1 to N.
